name: Node.js CI

on:
  push:
    branches: ['**']
    tags:
      - v*
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run generate
      - run: npm run test
      - run: npm run build
      - run: rm -r ./.next/cache
      - name: Gamejutsu Frontend Build
        id: gamejutsu-frontend-build
        uses: actions/upload-artifact@v3
        with:
          name: gamejutsu-frontend-build-${{ github.run_id }}
          path: ./.next

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: ls -l
      - run: ls -l ./gamejutsu-frontend-build-${{ github.run_id }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Copy artifact to server
        run: scp -r ./gamejutsu-frontend-build-${{ github.run_id }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gamejutsu@${{secrets.HOST}}:/home/gamejutsu/dev/build
